A guide on publishing micro services to DC/OS
typesafehub/prod-suite-management-doc pull request #1
Opened 2016-11-22 07:58 UTC by huntc

2016-11-22 07:59 UTC, huntc commented
FYI @eed3si9n - this should hopefully be within your guidelines.

2016-11-22 08:32 UTC, markusjura requested changes
Overall, great documentation!

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +* removing the Cassandra deployment from the installation script given that DC/OS will be hosting Cassandra; and
Would be nice to add an option to the installation script to not include Cassandra into it.

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +* removing the Cassandra deployment from the installation script given that DC/OS will be hosting Cassandra; and
Another option could tell if `dcos conduct` or `conduct` should be used

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +What we'll do in this guide is use [ConductR](http://conductr.lightbend.com/) to deploy your Lagom service. ConductR 2.0 can operate either in a stand-alone manner or as a Mesos framework\*. ConductR
Unneccearry comma: `with Mesos in mind,`

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +> As at the time of writing ConductR 2.0 is available as an Early Access release and can be obtained by [contacting our sales department](https://www.lightbend.com/contact). We will also be offering
Missing comma after `Meanwhile`

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +We are not finished though - we must first provide some configuration for each service that will declare how to locate Cassandra on DC/OS. This is described next...
Missing comma between `finished, though`

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +Let's now re-visit our installation script.
Use `revisit` instead of `re-visit`

2016-11-22 08:32 UTC, markusjura commented on guides/dcos-microservices/src/main/paradox/index.md
> +Note then that a bundle's configuration is supplied as the second parameter to the `load` sub command.
`subcommand` instead of `sub command`

2016-11-22 12:38 UTC, jonas commented on guides/dcos-microservices/src/main/paradox/index.md
> +> As at the time of writing ConductR 2.0 is available as an Early Access release and can be obtained by [contacting our sales department](https://www.lightbend.com/contact). We will also be offering
Paradox 0.2.6 has the `@@@ note` directive which might be a better way to make this standout.

2016-11-22 18:19 UTC, huntc commented
Thanks!

2016-11-23 00:25 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +* removing the Cassandra deployment from the installation script given that DC/OS will be hosting Cassandra; and
Perhaps - not part of this PR though.

2016-11-23 00:25 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +We are not finished though - we must first provide some configuration for each service that will declare how to locate Cassandra on DC/OS. This is described next...
There shouldn't be one there.

2016-11-23 00:26 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +Let's now re-visit our installation script.
ok

2016-11-23 00:26 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +Note then that a bundle's configuration is supplied as the second parameter to the `load` sub command.
Disagree

2016-11-23 00:26 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +What we'll do in this guide is use [ConductR](http://conductr.lightbend.com/) to deploy your Lagom service. ConductR 2.0 can operate either in a stand-alone manner or as a Mesos framework\*. ConductR
ok

2016-11-23 00:26 UTC, huntc commented on guides/dcos-microservices/src/main/paradox/index.md
> +> As at the time of writing ConductR 2.0 is available as an Early Access release and can be obtained by [contacting our sales department](https://www.lightbend.com/contact). We will also be offering
ok

2016-11-23 00:34 UTC, merged